---
- name: Template for copying files
  hosts: nodesubgroup
  become: yes

  tasks:
    - name: Copies a file from src to dest
      ansible.builtin.copy:
        src: /home/celebrimbor/projects/lenovo-cluster/config_files/network/eduroam/eduroam.nmconnection
        dest: /etc/NetworkManager/system-connections/eduroam.nmconnection
